[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = {git = "https://github.com/yewstack/yew/", features=["csr"]}

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
